version: '3.8'

services:
  database:
    image: mysql:5.7.31
    restart: on-failure
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - "3306:3306"
  application:
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      MYSQL_HOST: 'database'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      PORT: '3000'
    ports:
      - "3000:3000"
    depends_on:
      - database
